# Updated docker-compose.yml with own images
# Replace with own DockerHub username

services:
  vote:
    image: prouan/vote:latest
    # build: ./vote  # You can keep this commented as backup
    depends_on:
      redis:
        condition: service_healthy 
    ports:
      - "8080:80"
    networks:
      - back-tier
    environment:
      - REDIS_HOST=redis  # Points to the redis service name

  result:
    image: prouan/result:latest
    # build: ./result  # You can keep this commented as backup
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "8081:80"
    networks:
      - back-tier
    environment:
      - PG_HOST=db  # Points to the postgres service name

  worker:
    image: prouan/worker:latest
    # build: ./worker  # You can keep this commented as backup
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    networks:
      - back-tier
    environment:
      - REDIS_HOST=redis  # Points to the redis service name
      - DB_HOST=db       # Points to the postgres service name

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
